spring.application.name=telegram.bot

# config tg-bot
telegram.bot.name=TaskTrackerForHoroshyeRebyataBot
telegram.bot.token=7354149926:AAEGAP9C_r3yumB6m6wrjU767gdZ1adySq8

# config database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=task_tracker
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.default-schema=task_tracker
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# database logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true